
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 150
#define YY_END_OF_BUFFER 151
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[517] =
    {   0,
        0,    0,  151,  149,    2,    1,   35,  149,  149,   26,
       29,  149,   13,   14,   24,   22,   66,   23,   20,   25,
      135,  135,   16,   15,   38,   37,   39,   18,  132,  132,
        9,   11,   27,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,    5,   31,    7,   33,    2,   56,    0,
      140,    0,    0,   44,    8,   60,   47,    0,  138,    0,
       42,   64,   40,   65,   41,   68,   21,    0,  136,    3,
        4,   43,  136,  134,  135,    0,  135,  135,    0,   19,
       12,    6,   10,   51,   58,   55,   59,   52,  132,    0,

        0,   45,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,   82,  132,  132,  132,  132,  132,  132,
      132,  132,  132,   95,  132,  132,  132,  132,  132,  132,
      132,   63,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
       49,   62,    0,  140,    0,    0,    0,  138,    0,   67,
       17,    0,  136,  134,  134,    0,  137,  135,  135,  133,
       53,   54,    0,  141,    0,    0,  139,    0,   61,   69,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,

       92,  132,  132,  132,   97,  132,  132,  132,  101,   36,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  120,  132,
      132,  132,  132,  132,  132,  132,  132,  132,   28,    0,
        0,  136,  134,  134,  137,  133,  133,    0,  141,    0,
        0,  139,    0,  132,   70,  132,  132,   71,  132,   73,
      132,   75,  132,  132,  132,  132,  132,  132,  132,  132,
       85,   86,  132,  132,  132,  132,  132,  132,   94,  132,
       98,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  117,

      132,  119,  132,  132,  132,  132,  132,  128,  132,  132,
      132,  132,    0,  133,  133,  132,  132,   32,   72,   74,
       76,   34,   77,  132,  132,  132,  132,  132,  132,  132,
      132,   90,   91,  132,  132,  132,  132,  132,  132,   50,
      132,  132,  132,  132,  132,  132,  109,  132,  132,  132,
      132,  132,  132,  118,  132,  132,  132,  124,  132,  126,
      132,  132,  132,  131,  132,    0,   48,   30,  132,  132,
      132,   81,   83,  132,  132,   88,   89,   93,   96,  132,
      132,   57,  132,  132,  132,  105,  132,  132,  108,  110,
      111,  112,  114,  115,  132,  132,  122,  132,  132,    0,

      132,  132,  132,   46,    0,  132,  132,   80,  132,  132,
       99,  132,  132,  103,  132,  132,  132,  132,  132,  121,
      132,  132,    0,  127,  132,  130,    0,  132,   79,  132,
       87,  132,  102,  132,  106,  132,  132,  116,  123,  125,
        0,  129,    0,    0,  132,  132,  100,  104,  132,  132,
        0,    0,    0,    0,   78,  132,  132,  132,    0,    0,
        0,    0,    0,    0,  132,  132,  113,    0,    0,    0,
        0,    0,    0,    0,   84,  132,    0,    0,    0,    0,
        0,    0,    0,  132,    0,    0,    0,    0,    0,    0,
        0,  132,    0,  144,    0,  145,    0,    0,    0,  132,

        0,    0,    0,    0,  147,  107,    0,  143,  146,    0,
        0,  142,    0,    0,  148,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   28,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   31,
       31,   31,   31,   31,   33,   31,   31,   34,   31,   31,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   31,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   65,   66,   67,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[69] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        2,    1,    1,    1,    1,    1,    1,    2,    2,    2,
        3,    3,    3,    3,    1,    1,    1,    1,    3,    2,
        2,    2,    2,    2,    2,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[527] =
    {   0,
        0,    0,  673,  674,   67,  674,  647,   64,  623,   47,
       65,   65,  674,  674,  645,   62,  674,   63,   64,   73,
       85,   92,   56,  674,   72,  644,   67,  674,    0,   89,
      674,  674,  643,   51,   67,   87,   63,   81,   99,  614,
       93,  613,  606,   88,   92,   94,  620,  109,  115,  106,
      112,  119,  610,  674,  129,  674,  674,  170,  674,  158,
      674,  170,  610,  674,  674,  674,  674,  165,  674,  174,
      674,  674,  674,  674,  674,  648,  674,  643,  167,  674,
      674,  674,  184,  203,  222,  244,  148,  148,    0,  674,
      674,  674,  674,  634,  674,  674,  674,  633,    0,  173,

      172,  674,  614,  605,  597,  596,  600,  608,  111,  611,
      610,  138,  176,  590,  596,  590,  587,  161,  595,  591,
      587,  594,  583,    0,   72,  588,  581,  587,  576,  578,
      591,  595,  177,  592,  192,  579,  154,  193,  583,  579,
      135,  168,  575,  145,  580,  571,  196,  579,  577,  568,
      674,  674,  231,  239,  253,  581,  238,  242,  258,  674,
      674,  263,  674,  236,  238,  266,  271,  674,  674,  264,
      674,  674,  270,  674,  296,  283,  674,  295,  583,    0,
      568,  260,  570,  579,  574,  575,  560,  558,  560,  250,
      573,  568,  570,  570,  565,  557,  259,  563,  549,  565,

        0,  560,  550,  554,    0,  555,  560,  555,    0,  559,
      541,  552,  535,  536,  543,  544,  539,  531,  533,  536,
      543,  528,  526,  526,  529,  525,  528,  536,    0,  535,
      525,  529,  524,  517,  531,  533,  532,  521,  531,  519,
      305,  308,  674,  674,  674,  271,  283,  274,  305,  314,
      308,  312,  332,  524,    0,  515,  510,    0,  516,    0,
      517,    0,  506,  512,  503,  512,  500,  500,  507,  505,
        0,    0,  507,  498,  497,  508,  493,  498,    0,  497,
        0,  507,  490,  502,  505,  489,  503,  498,  493,  483,
      481,  482,  479,  492,  482,  486,  491,  490,  481,    0,

      469,    0,  291,  477,  482,  481,  467,    0,  467,  468,
      479,  478,  462,  674,  674,  465,  476,    0,    0,    0,
        0,    0,  479,  465,  466,  471,  470,  465,  470,  453,
      458,    0,    0,  466,  464,  457,  452,  450,  446,    0,
      445,  460,  459,  442,  455,  446,    0,  454,  451,  453,
      436,  446,  452,    0,  447,  447,  449,    0,  436,  483,
      446,  437,  445,    0,  428,  439,    0,    0,  439,  421,
      421,    0,    0,  436,  429,    0,    0,    0,    0,  432,
      435,    0,  421,  429,  414,    0,  427,  414,    0,    0,
        0,  430,    0,    0,  410,  422,    0,  415,  421,  412,

      413,  412,  403,    0,  416,  419,  414,    0,  418,  398,
        0,  413,  398,    0,  409,  396,  397,  408,  405,    0,
      404,  404,  406,    0,  401,    0,  332,  387,    0,  401,
        0,  398,    0,  398,    0,  384,  399,    0,    0,    0,
      387,    0,  333,  303,  379,  396,    0,    0,  391,  377,
      389,  304,  379,  373,    0,  373,  371,  370,  370,  386,
      367,  376,  295,  367,  364,  382,    0,  366,  361,  375,
      366,  376,  357,  366,    0,  371,  372,  364,  360,  365,
      356,  351,  354,  365,  362,  377,  354,  375,  352,  355,
      352,  340,  352,  674,  354,  674,  313,  326,  339,  306,

      359,  333,  328,  298,  674,    0,  290,  674,  674,  247,
      213,  674,  214,  169,  674,  674,  368,  371,  373,  376,
      379,  183,  382,  385,  388,  391
    } ;

static yyconst flex_int16_t yy_def[527] =
    {   0,
      516,    1,  516,  516,  516,  516,  516,  517,  516,  516,
      516,  518,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  519,  519,
      516,  516,  516,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  516,  516,  516,  516,  516,  516,  517,
      516,  520,  516,  516,  516,  516,  516,  518,  516,  521,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  522,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  519,  523,

      524,  516,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      516,  516,  517,  517,  520,  516,  518,  518,  521,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  522,
      516,  516,  523,  516,  525,  524,  516,  526,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,

      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  516,
      516,  516,  516,  516,  516,  516,  516,  523,  523,  525,
      524,  524,  526,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,

      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  516,  516,  516,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  516,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  516,

      519,  519,  519,  519,  516,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  516,  519,  519,  519,  516,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      516,  519,  516,  516,  519,  519,  519,  519,  519,  519,
      516,  516,  516,  516,  519,  519,  519,  519,  516,  516,
      516,  516,  516,  516,  519,  519,  519,  516,  516,  516,
      516,  516,  516,  516,  519,  519,  516,  516,  516,  516,
      516,  516,  516,  519,  516,  516,  516,  516,  516,  516,
      516,  519,  516,  516,  516,  516,  516,  516,  516,  519,

      516,  516,  516,  516,  516,  519,  516,  516,  516,  516,
      516,  516,  516,  516,  516,    0,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516
    } ;

static yyconst flex_uint16_t yy_nxt[743] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   29,
       29,   30,   29,   29,   31,    4,   32,   33,   29,   34,
       35,   36,   37,   38,   39,   40,   29,   41,   29,   42,
       43,   44,   45,   46,   29,   47,   48,   49,   50,   51,
       52,   53,   29,   29,   54,   55,   56,   57,   58,   61,
       58,   64,   65,   66,   69,   72,   77,   90,   74,   92,
       78,   91,   79,   79,   79,   80,   73,   75,   76,   67,
       81,   97,   98,   93,  100,   94,   95,   82,  101,   62,

       70,   83,  103,   84,   84,   85,  113,  104,   83,  105,
       85,   85,   85,   86,  106,  114,   87,   88,   89,  107,
       86,  204,  108,   87,   88,  115,  109,  128,   86,  205,
      116,  129,  117,  110,   87,   86,  111,  124,  119,  112,
      130,   87,  118,   88,  125,  131,   89,  132,  120,  133,
       88,  121,  134,  151,  122,  136,  137,  144,  140,  146,
      148,  141,  145,   61,  147,  149,  138,  185,  186,  139,
      142,   58,   60,   58,   69,  154,   68,  143,  174,  169,
      168,  177,  226,  158,  170,   79,   79,   79,  189,  190,
      227,  515,  231,   62,  152,  162,  163,  169,  163,  220,

       70,  232,   79,   79,   79,  155,  168,  178,  175,  159,
      162,  163,  162,  163,  197,  163,  163,  221,  198,   83,
      191,   84,   84,   85,  213,  192,  228,  162,  163,  214,
      229,   86,  222,  163,  164,  165,   61,  216,   83,  217,
       85,   85,   85,  235,   61,  236,   86,   69,  223,  218,
       86,   69,  164,   87,   88,   60,  514,  166,  154,  166,
       68,  165,  167,  167,  167,   86,   62,  158,  243,  244,
      513,   87,  512,   70,   62,  174,  241,   70,  241,  174,
       88,  242,  242,  242,  167,  167,  167,  244,  155,  167,
      167,  167,  177,  159,  243,  246,  247,  176,  173,  256,

      245,  249,  245,  314,  252,  175,  265,  266,  273,  175,
      174,  274,  257,  246,  315,  245,  173,  177,  178,  249,
      245,  177,  247,  242,  242,  242,  242,  242,  242,  314,
      253,  250,  315,  355,  176,  443,  443,  163,  356,  163,
      175,  252,  357,  178,  452,  472,  511,  178,  510,  250,
      453,  473,  163,  509,  460,  444,  444,  163,  508,  454,
      461,  462,  507,  506,  505,  504,  503,  253,   60,   60,
       60,   68,   68,   68,   99,   99,  153,  153,  153,  157,
      157,  157,  173,  173,  173,  176,  176,  176,  248,  248,
      248,  251,  251,  251,  502,  501,  500,  499,  498,  497,

      496,  495,  494,  493,  492,  491,  490,  489,  488,  487,
      486,  485,  484,  483,  482,  481,  480,  479,  478,  477,
      476,  475,  474,  471,  470,  469,  468,  467,  466,  465,
      464,  463,  459,  458,  457,  456,  455,  451,  450,  449,
      448,  447,  446,  445,  442,  441,  440,  439,  438,  437,
      436,  435,  434,  433,  432,  431,  430,  429,  428,  427,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  417,
      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,
      406,  405,  404,  403,  402,  401,  400,  399,  398,  397,
      396,  395,  394,  393,  392,  391,  390,  389,  388,  387,

      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  354,
      353,  352,  351,  350,  349,  348,  347,  346,  345,  344,
      343,  342,  341,  340,  339,  338,  337,  336,  335,  334,
      333,  332,  331,  330,  329,  328,  327,  326,  325,  324,
      323,  322,  321,  320,  319,  318,  317,  316,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      301,  300,  299,  298,  297,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  282,

      281,  280,  279,  278,  277,  276,  275,  272,  271,  270,
      269,  268,  267,  264,  263,  262,  261,  260,  259,  258,
      255,  254,  240,  239,  238,  237,  234,  233,  230,  225,
      224,  219,  215,  212,  211,  210,  209,  208,  207,  206,
      203,  202,  201,  200,  199,  196,  195,  194,  193,  188,
      187,  184,  183,  182,  181,  180,  179,  172,  171,  161,
      160,  156,  150,  135,  127,  126,  123,  102,   96,   71,
       63,   59,  516,    3,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,

      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516
    } ;

static yyconst flex_int16_t yy_chk[743] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    8,
        5,   10,   10,   11,   12,   16,   19,   23,   18,   25,
       19,   23,   19,   19,   19,   20,   16,   18,   18,   11,
       20,   27,   27,   25,   30,   25,   25,   20,   30,    8,

       12,   21,   34,   21,   21,   21,   37,   34,   22,   34,
       22,   22,   22,   21,   35,   37,   21,   21,   21,   35,
       22,  125,   35,   22,   22,   37,   36,   44,   21,  125,
       38,   44,   38,   36,   21,   22,   36,   41,   39,   36,
       44,   22,   38,   21,   41,   45,   21,   45,   39,   46,
       22,   39,   46,   55,   39,   48,   48,   50,   49,   51,
       52,   49,   50,   60,   51,   52,   48,  109,  109,   48,
       49,   58,   62,   58,   68,   62,   70,   49,  100,   88,
       87,  101,  141,   70,  522,   79,   79,   79,  112,  112,
      141,  514,  144,   60,   55,   79,   79,   88,   79,  137,

       68,  144,   83,   83,   83,   62,   87,  101,  100,   70,
       79,   79,   83,   83,  118,   83,   79,  137,  118,   84,
      113,   84,   84,   84,  133,  113,  142,   83,   83,  133,
      142,   84,  138,   83,   84,   84,  153,  135,   85,  135,
       85,   85,   85,  147,  154,  147,   84,  157,  138,  135,
       85,  158,   84,   85,   85,  155,  513,   86,  155,   86,
      159,   84,   86,   86,   86,   85,  153,  159,  164,  165,
      511,   85,  510,  157,  154,  173,  162,  158,  162,  248,
       85,  162,  162,  162,  166,  166,  166,  165,  155,  167,
      167,  167,  176,  159,  164,  170,  170,  178,  175,  182,

      167,  175,  167,  246,  178,  173,  190,  190,  197,  248,
      249,  197,  182,  170,  247,  167,  250,  251,  176,  250,
      167,  252,  170,  241,  241,  241,  242,  242,  242,  246,
      178,  175,  247,  303,  253,  427,  443,  242,  303,  242,
      249,  253,  303,  251,  444,  463,  507,  252,  504,  250,
      444,  463,  242,  503,  452,  427,  443,  242,  502,  444,
      452,  452,  501,  500,  499,  498,  497,  253,  517,  517,
      517,  518,  518,  518,  519,  519,  520,  520,  520,  521,
      521,  521,  523,  523,  523,  524,  524,  524,  525,  525,
      525,  526,  526,  526,  495,  493,  492,  491,  490,  489,

      488,  487,  486,  485,  484,  483,  482,  481,  480,  479,
      478,  477,  476,  474,  473,  472,  471,  470,  469,  468,
      466,  465,  464,  462,  461,  460,  459,  458,  457,  456,
      454,  453,  451,  450,  449,  446,  445,  441,  437,  436,
      434,  432,  430,  428,  425,  423,  422,  421,  419,  418,
      417,  416,  415,  413,  412,  410,  409,  407,  406,  405,
      403,  402,  401,  400,  399,  398,  396,  395,  392,  388,
      387,  385,  384,  383,  381,  380,  375,  374,  371,  370,
      369,  366,  365,  363,  362,  361,  360,  359,  357,  356,
      355,  353,  352,  351,  350,  349,  348,  346,  345,  344,

      343,  342,  341,  339,  338,  337,  336,  335,  334,  331,
      330,  329,  328,  327,  326,  325,  324,  323,  317,  316,
      313,  312,  311,  310,  309,  307,  306,  305,  304,  301,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  280,  278,
      277,  276,  275,  274,  273,  270,  269,  268,  267,  266,
      265,  264,  263,  261,  259,  257,  256,  254,  240,  239,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  228,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  216,  215,  214,  213,  212,  211,  210,  208,  207,

      206,  204,  203,  202,  200,  199,  198,  196,  195,  194,
      193,  192,  191,  189,  188,  187,  186,  185,  184,  183,
      181,  179,  156,  150,  149,  148,  146,  145,  143,  140,
      139,  136,  134,  132,  131,  130,  129,  128,  127,  126,
      123,  122,  121,  120,  119,  117,  116,  115,  114,  111,
      110,  108,  107,  106,  105,  104,  103,   98,   94,   78,
       76,   63,   53,   47,   43,   42,   40,   33,   26,   15,
        9,    7,    3,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,

      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "120lex.l"
/*	$Id: lexer.l,v 1.2 1997/11/19 15:13:15 sandro Exp $	*/
/*
 * Copyright (c) 1997 Sandro Sigala <ssigala@globalnet.it>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * ISO C++ lexical analyzer.
 *
 * Based on the ISO C++ draft standard of December '96.
 */
#line 35 "120lex.l"
#define YYDEBUG 1
    
#include <ctype.h>
#include <stdio.h>

#include "token.h"
#include "tree.h"
#include "120gram.tab.h"
#include "sym.h"
//#include "parser.h"

extern int yylex();
extern char *fileName;
extern void addNode();
extern void initToken();
extern table *globalTable;

int lineno = 0;
int saw_iostream, saw_string, saw_std, saw_cstdlib; 
int saw_ctime, saw_cmath, saw_iomanip;
int yy_add( int i );
char *yy_format( char *t );

static int yywrap(void);
static void skip_until_eol(void);
static void skip_comment(void);
static int check_identifier(char *);
int typenametable_insert(char *s, int cat);
#line 847 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

			int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 72 "120lex.l"


#line 1068 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 517 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 674 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 74 "120lex.l"
{ ++lineno; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 75 "120lex.l"
{ /* Ignore whitespace. */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 77 "120lex.l"
{ skip_comment(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 78 "120lex.l"
{ skip_until_eol(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 80 "120lex.l"
{ return yy_add('{'); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 81 "120lex.l"
{ return yy_add('{'); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 82 "120lex.l"
{ return yy_add('}'); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 83 "120lex.l"
{ return yy_add('}'); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 84 "120lex.l"
{ return yy_add('['); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 85 "120lex.l"
{ return yy_add('['); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 86 "120lex.l"
{ return yy_add(']'); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 87 "120lex.l"
{ return yy_add(']'); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 88 "120lex.l"
{ return yy_add('('); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 89 "120lex.l"
{ return yy_add(')'); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 90 "120lex.l"
{ return yy_add(';'); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 91 "120lex.l"
{ return yy_add(':'); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 92 "120lex.l"
{ return yy_add(ELLIPSIS); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 93 "120lex.l"
{ return yy_add('?'); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 94 "120lex.l"
{ return yy_add(COLONCOLON); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 95 "120lex.l"
{ return yy_add('.'); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 96 "120lex.l"
{ return yy_add(DOTSTAR); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 97 "120lex.l"
{ return yy_add('+'); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 98 "120lex.l"
{ return yy_add('-'); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 99 "120lex.l"
{ return yy_add('*'); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 100 "120lex.l"
{ return yy_add('/'); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 101 "120lex.l"
{ return yy_add('%'); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 102 "120lex.l"
{ return yy_add('^'); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 103 "120lex.l"
{ return yy_add('^'); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 104 "120lex.l"
{ return yy_add('&'); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 105 "120lex.l"
{ return yy_add('&'); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 106 "120lex.l"
{ return yy_add('|'); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 107 "120lex.l"
{ return yy_add('|'); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 108 "120lex.l"
{ return yy_add('~'); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 109 "120lex.l"
{ return yy_add('~'); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 110 "120lex.l"
{ return yy_add('!'); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 111 "120lex.l"
{ return yy_add('!'); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 112 "120lex.l"
{ return yy_add('='); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 113 "120lex.l"
{ return yy_add('<'); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 114 "120lex.l"
{ return yy_add('>'); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 115 "120lex.l"
{ return yy_add(ADDEQ); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 116 "120lex.l"
{ return yy_add(SUBEQ); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 117 "120lex.l"
{ return yy_add(MULEQ); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 118 "120lex.l"
{ return yy_add(DIVEQ); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 119 "120lex.l"
{ return yy_add(MODEQ); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 120 "120lex.l"
{ return yy_add(XOREQ); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 121 "120lex.l"
{ return yy_add(XOREQ); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 122 "120lex.l"
{ return yy_add(ANDEQ); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 123 "120lex.l"
{ return yy_add(ANDEQ); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 124 "120lex.l"
{ return yy_add(OREQ); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 125 "120lex.l"
{ return yy_add(OREQ); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 126 "120lex.l"
{ return yy_add(SL); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 127 "120lex.l"
{ return yy_add(SR); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 128 "120lex.l"
{ return yy_add(SLEQ); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 129 "120lex.l"
{ return yy_add(SREQ); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 130 "120lex.l"
{ return yy_add(EQ); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 131 "120lex.l"
{ return yy_add(NOTEQ); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 132 "120lex.l"
{ return yy_add(NOTEQ); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 133 "120lex.l"
{ return yy_add(LTEQ); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 134 "120lex.l"
{ return yy_add(GTEQ); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 135 "120lex.l"
{ return yy_add(ANDAND); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 136 "120lex.l"
{ return yy_add(ANDAND); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 137 "120lex.l"
{ return yy_add(OROR); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 138 "120lex.l"
{ return yy_add(OROR); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 139 "120lex.l"
{ return yy_add(PLUSPLUS); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 140 "120lex.l"
{ return yy_add(MINUSMINUS); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 141 "120lex.l"
{ return yy_add(','); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 142 "120lex.l"
{ return yy_add(ARROWSTAR); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 143 "120lex.l"
{ return yy_add(ARROW); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 145 "120lex.l"
{ return yy_add(ASM); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 146 "120lex.l"
{ return yy_add(AUTO); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 147 "120lex.l"
{ return yy_add(BOOL); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 148 "120lex.l"
{ return yy_add(BREAK); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 149 "120lex.l"
{ return yy_add(CASE); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 150 "120lex.l"
{ return yy_add(CATCH); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 151 "120lex.l"
{ return yy_add(CHAR); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 152 "120lex.l"
{ return yy_add(CLASS); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 153 "120lex.l"
{ return yy_add(CONST); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 154 "120lex.l"
{ return yy_add(CONST_CAST); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 155 "120lex.l"
{ return yy_add(CONTINUE); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 156 "120lex.l"
{ return yy_add(DEFAULT); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 157 "120lex.l"
{ return yy_add(DELETE); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 158 "120lex.l"
{ return yy_add(DO); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 159 "120lex.l"
{ return yy_add(DOUBLE); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 160 "120lex.l"
{ return yy_add(DYNAMIC_CAST); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 161 "120lex.l"
{ return yy_add(ELSE); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 162 "120lex.l"
{ return yy_add(ENUM); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 163 "120lex.l"
{ return yy_add(EXPLICIT); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 164 "120lex.l"
{ return yy_add(EXPORT); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 165 "120lex.l"
{ return yy_add(EXTERN); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 166 "120lex.l"
{ return yy_add(FALSE); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 167 "120lex.l"
{ return yy_add(FLOAT); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 168 "120lex.l"
{ return yy_add(FOR); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 169 "120lex.l"
{ return yy_add(FRIEND); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 170 "120lex.l"
{ return yy_add(GOTO); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 171 "120lex.l"
{ return yy_add(IF); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 172 "120lex.l"
{ return yy_add(INLINE); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 173 "120lex.l"
{ return yy_add(INT); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 174 "120lex.l"
{ return yy_add(LONG); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 175 "120lex.l"
{ return yy_add(MUTABLE); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 176 "120lex.l"
{ return yy_add(NAMESPACE); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 177 "120lex.l"
{ return yy_add(NEW); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 178 "120lex.l"
{ return yy_add(OPERATOR); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 179 "120lex.l"
{ return yy_add(PRIVATE); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 180 "120lex.l"
{ return yy_add(PROTECTED); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 181 "120lex.l"
{ return yy_add(PUBLIC); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 182 "120lex.l"
{ return yy_add(REGISTER); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 183 "120lex.l"
{ return yy_add(REINTERPRET_CAST); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 184 "120lex.l"
{ return yy_add(RETURN); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 185 "120lex.l"
{ return yy_add(SHORT); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 186 "120lex.l"
{ return yy_add(SIGNED); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 187 "120lex.l"
{ return yy_add(SIZEOF); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 188 "120lex.l"
{ return yy_add(STATIC); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 189 "120lex.l"
{ return yy_add(STATIC_CAST); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 190 "120lex.l"
{ return yy_add(STRUCT); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 191 "120lex.l"
{ return yy_add(SWITCH); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 192 "120lex.l"
{ return yy_add(TEMPLATE); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 193 "120lex.l"
{ return yy_add(THIS); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 194 "120lex.l"
{ return yy_add(THROW); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 195 "120lex.l"
{ return yy_add(TRUE); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 196 "120lex.l"
{ return yy_add(TRY); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 197 "120lex.l"
{ return yy_add(TYPEDEF); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 198 "120lex.l"
{ return yy_add(TYPEID); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 199 "120lex.l"
{ return yy_add(TYPENAME); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 200 "120lex.l"
{ return yy_add(UNION); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 201 "120lex.l"
{ return yy_add(UNSIGNED); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 202 "120lex.l"
{ return yy_add(USING); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 203 "120lex.l"
{ return yy_add(VIRTUAL); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 204 "120lex.l"
{ return yy_add(VOID); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 205 "120lex.l"
{ return yy_add(VOLATILE); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 206 "120lex.l"
{ return yy_add(WCHAR_T); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 207 "120lex.l"
{ return yy_add(WHILE); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 209 "120lex.l"
{ return yy_add(IDENTIFIER); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 211 "120lex.l"
{ return yy_add(INTEGER); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 212 "120lex.l"
{ return yy_add(INTEGER); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 213 "120lex.l"
{ return yy_add(INTEGER); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 215 "120lex.l"
{ return yy_add(FLOATING); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 216 "120lex.l"
{ return yy_add(FLOATING); }
	YY_BREAK
case 138:
/* rule 138 can match eol */
YY_RULE_SETUP
#line 218 "120lex.l"
{ return yy_add(CHARACTER); }
	YY_BREAK
case 139:
/* rule 139 can match eol */
YY_RULE_SETUP
#line 219 "120lex.l"
{ return yy_add(CHARACTER); }
	YY_BREAK
case 140:
/* rule 140 can match eol */
YY_RULE_SETUP
#line 221 "120lex.l"
{ return yy_add(STRING); }
	YY_BREAK
case 141:
/* rule 141 can match eol */
YY_RULE_SETUP
#line 222 "120lex.l"
{ return yy_add(STRING); }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 223 "120lex.l"
{ saw_iostream = 1; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 224 "120lex.l"
{ saw_cstdlib = 1; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 225 "120lex.l"
{ saw_cmath = 1; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 226 "120lex.l"
{ saw_ctime = 1; }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 227 "120lex.l"
{ saw_iomanip = 1; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 228 "120lex.l"
{ saw_string = 1; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 229 "120lex.l"
{ saw_std = 1; 
                            token *t;
                            if(saw_string) tableInsert(globalTable, "string", NULL);
                            if(saw_iostream) {
                                tableInsert(globalTable, "ifstream", NULL);
                                tableInsert(globalTable, "ofstream", NULL);
                            }
                            if(saw_cstdlib) {}
                            if(saw_cmath) {}
                            if(saw_ctime) {}
                            if(saw_iomanip) {}
                        }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 243 "120lex.l"
{ fprintf(stderr, "%d: unexpected character `%c'\n", lineno, yytext[0]); }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 245 "120lex.l"
ECHO;
	YY_BREAK
#line 1891 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 517 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 517 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 516);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 245 "120lex.l"



static int
yywrap(void)
{
	return 1;
}

/*
 * We use this routine instead a lex pattern because we don't need
 * to save the matched comment in the `yytext' buffer.
 */
static void
skip_comment(void)
{
	int c1, c2;

	c1 = input();
	c2 = input();

	while (c2 != EOF && !(c1 == '*' && c2 == '/')) {
		if (c1 == '\n')
			++lineno;
		c1 = c2;
		c2 = input();
	}
}

/*
 * See the previous comment for an explanation.
 */
static void
skip_until_eol(void)
{
	int c;

	while ((c = input()) != EOF && c != '\n')
		;
	++lineno;
}

/*
 * Type name table.
 * Replace this with a hash table, when you get a chance.
 */
struct typenametable_entry {
   char *name;
   int category;
   struct typenametable_entry *next;
   } *head;

int typenametable_lookup(char *s)
{
   struct typenametable_entry *tmp = head;
   while (tmp) {
      if (!strcmp(s, tmp->name)) return tmp->category;
      tmp = tmp->next;
   }
   return IDENTIFIER;
}

int typenametable_insert(char *s, int cat)
{
   struct typenametable_entry *tmp = head;
   while (tmp) {
      if (!strcmp(s, tmp->name)) {
         fprintf(stderr,
	    "warning, %s is already in the typename table as a %d\n",
	    s, tmp->category );
         return tmp->category;
         }
      tmp = tmp->next;
   }
   tmp = calloc(1, sizeof (struct typenametable_entry));
   if(!tmp) { fprintf(stderr, "tnti out of memory\n"); return -1; }
   tmp->name = strdup(s);
   tmp->category = cat;
   tmp->next = head;
   head = tmp;
}

static int
check_identifier(char *s)
{
	return typenametable_lookup(s);
}

// Main token creation function for each
int yy_add( int i ) {

    token *t = malloc(sizeof(token));
    initToken(t);
    t->text = strdup(yytext);

    // Switch to look for svals and ivals
    switch(i) {

        case INTEGER:
        case FLOATING:
            t->ival = atoi(yytext);
            break;
        case CHARACTER:
            t->sval = strdup(yytext);
            break;
        case IDENTIFIER:
        case STRING:
            t->sval = strdup(yytext);
            //if(t->sval != NULL)fprintf(stderr,"In string or identifier, t->sval = %s\n", t->sval);
            break;
    }
    t->category = i;
    t->filename = fileName;
    t->lineno = lineno;
    // Malloc the tree node and set t as its leaf
    yylval = malloc(sizeof(struct tree));
    yylval->u.leaf = t;
    return i;
}

char *yy_format( char *t ) {

    int size = strlen(t)-1;
    if(size>64) size = 64;
    char *temp = malloc(sizeof(char)*size);
    if( t == NULL && size < 1 ) return NULL;
    for( int i = 0; i < size-2; i++ ) {
        
        temp[i] = t[i+1];
    }
    temp[size-1] = '\n';
    return temp;
}
